name: information-noise-reduction-for-investors
channels:
  - defaults
dependencies:
  - python=3.11.5
  - numpy
  - pandas
  - scikit-learn
  - tensorflow
  - keras
  - matplotlib
  - opencv
  - kagglehub
  - pip
  - ipykernel
  - jupyter
  - pip:
    - keras-tuner